"""add new columns to market_info

Revision ID: 256bff7750e9
Revises: a7e64a7ffeef
Create Date: 2025-04-26 17:37:21.765810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256bff7750e9'
down_revision: Union[str, None] = 'a7e64a7ffeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_info', sa.Column('turnover', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('market_info', sa.Column('share_volume', sa.Integer(), nullable=True))
    op.add_column('market_info', sa.Column('trade_volume', sa.Integer(), nullable=True))
    op.add_column('market_info', sa.Column('beta', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_info', 'beta')
    op.drop_column('market_info', 'trade_volume')
    op.drop_column('market_info', 'share_volume')
    op.drop_column('market_info', 'turnover')
    # ### end Alembic commands ###
