"""Add Source Field

Revision ID: 2684ce8c6bf4
Revises: dc034b7d770b
Create Date: 2025-01-17 17:50:15.084181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2684ce8c6bf4'
down_revision: Union[str, None] = 'dc034b7d770b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('source', sa.Enum('USER', 'BOT', name='messagesource'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'source')
    # ### end Alembic commands ###
