"""Rename message to content

Revision ID: 4ed3626769ff
Revises: ea4d03ec488b
Create Date: 2025-05-26 22:02:20.892759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ed3626769ff'
down_revision: Union[str, None] = 'ea4d03ec488b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagesource'), nullable=True))
    op.drop_column('chat_message', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('source', mysql.ENUM('USER', 'BOT'), nullable=True))
    op.drop_column('chat_message', 'role')
    # ### end Alembic commands ###
