"""add other company info

Revision ID: 87a25773e397
Revises: a31796dc7031
Create Date: 2025-03-21 21:26:04.234966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a25773e397'
down_revision: Union[str, None] = 'a31796dc7031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('stock_symbol', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('industry', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('founded', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'founded')
    op.drop_column('company', 'location')
    op.drop_column('company', 'industry')
    op.drop_column('company', 'stock_symbol')
    # ### end Alembic commands ###
