"""add new table company_metrics

Revision ID: 9edc9a1ef52d
Revises: 256bff7750e9
Create Date: 2025-04-26 20:30:52.068363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edc9a1ef52d'
down_revision: Union[str, None] = '256bff7750e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('beta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('earnings_per_share', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('market_info', sa.Column('hi_trade', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('market_info', sa.Column('low_trade', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_info', 'low_trade')
    op.drop_column('market_info', 'hi_trade')
    op.drop_table('company_metrics')
    # ### end Alembic commands ###
