"""increase description size

Revision ID: a31796dc7031
Revises: d488f30fde58
Create Date: 2025-03-16 18:08:19.921337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a31796dc7031'
down_revision: Union[str, None] = 'd488f30fde58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'description',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
