"""add new maket_info table

Revision ID: a7e64a7ffeef
Revises: 6b502d8459a4
Create Date: 2025-04-26 07:44:55.960954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e64a7ffeef'
down_revision: Union[str, None] = '6b502d8459a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('stock_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_info')
    # ### end Alembic commands ###
