"""Rename message to content

Revision ID: ea4d03ec488b
Revises: f37c88f43cb4
Create Date: 2025-05-26 22:00:52.774266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea4d03ec488b'
down_revision: Union[str, None] = 'f37c88f43cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('content', sa.String(length=5000), nullable=True))
    op.drop_column('chat_message', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('message', mysql.VARCHAR(length=5000), nullable=True))
    op.drop_column('chat_message', 'content')
    # ### end Alembic commands ###
