"""add new column financial_year

Revision ID: f37c88f43cb4
Revises: 9edc9a1ef52d
Create Date: 2025-04-28 10:52:50.614056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37c88f43cb4'
down_revision: Union[str, None] = '9edc9a1ef52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_metrics', sa.Column('financial_year', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_metrics', 'financial_year')
    # ### end Alembic commands ###
